#supervisor file for tops-api
[program:tops-status]
command=/srv/scripts/tops-status.sh
autostart=true
autorestart=true
delay=15
stderr_logfile=/var/log/tops-status.err.log
stdout_logfile=/var/log/tops-status.out.log
directory=/srv/apps/tops/api

user=root
