#supervisor file for tops-api
[program:tops-api]
command=/srv/scripts/tops-api.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/tops-api.err.log
stdout_logfile=/var/log/tops-api.out.log
directory=/srv/apps/tops/api

user=root
