#supervisor file for tops-api
[program:tops-scan-queue]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work sqs-audit --queue=teemops_audit --sleep=3 --tries=3 --max-time=3600
numprocs=8
autostart=true
autorestart=true
delay=15
stderr_logfile=/var/log/tops-scan-queue.err.log
stdout_logfile=/var/log/tops-scan-queue.out.log
directory=/srv/apps/tops
redirect_stderr=true
user=www-data
