#!/usr/bin/env bash
# Deploy Teemops messaging (SQS + S3 via SAM, SNS via CloudFormation) and write generated/teemops.env
set -euo pipefail

ROOT="${TEEMOPS_ROOT:-/workspace}"
CORE_DOCKER_DIR="${ROOT}/infra/cloud-stack/core-docker"
SNS_TEMPLATE="${ROOT}/infra/cloud-stack/stackset/sns.topic.cfn.yaml"
ENV_FILE="${ROOT}/generated/teemops.env"
LOG_FILE="${ROOT}/generated/install.log"

mkdir -p "${ROOT}/generated"

log() {
  echo "[installer] $*" | tee -a "$LOG_FILE"
}

die() {
  log "ERROR: $*"
  exit 1
}

load_dotenv() {
  if [[ -f "${ROOT}/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${ROOT}/.env"
    set +a
  fi
}

require_region() {
  export AWS_DEFAULT_REGION="${TOPS_DEPLOYMENT_REGION:?Set TOPS_DEPLOYMENT_REGION in .env or environment}"
  export AWS_REGION="$AWS_DEFAULT_REGION"
  log "Using AWS region: $AWS_DEFAULT_REGION"
}

validate_aws_auth() {
  if ! aws sts get-caller-identity --output json > "${ROOT}/generated/caller-identity.json" 2>>"$LOG_FILE"; then
    die "AWS credentials not configured. Mount ~/.aws or set AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY."
  fi
  local account_id
  account_id="$(python3 -c "import json; print(json.load(open('${ROOT}/generated/caller-identity.json'))['Account'])")"
  log "Authenticated as AWS account $account_id"
  export DETECTED_AWS_ACCOUNT_ID="$account_id"
}

cf_output() {
  local stack_name="$1"
  local output_key="$2"
  aws cloudformation describe-stacks \
    --stack-name "$stack_name" \
    --region "$AWS_DEFAULT_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='${output_key}'].OutputValue | [0]" \
    --output text 2>>"$LOG_FILE"
}

deploy_core_docker() {
  local environment="${TOPS_ENVIRONMENT:-test}"
  local stack_name="${TOPS_CORE_DOCKER_STACK:-teemops-core-docker}"

  log "Building SAM package (core-docker)..."
  (cd "$CORE_DOCKER_DIR" && sam build --cached --parallel 2>&1 | tee -a "$LOG_FILE")

  log "Deploying stack ${stack_name}..."
  (cd "$CORE_DOCKER_DIR" && sam deploy \
    --stack-name "$stack_name" \
    --region "$AWS_DEFAULT_REGION" \
    --no-confirm-changeset \
    --no-fail-on-empty-changeset \
    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
    --parameter-overrides "Environment=${environment}" \
    2>&1 | tee -a "$LOG_FILE")

  export CORE_STACK="$stack_name"
}

deploy_sns() {
  local environment="${TOPS_ENVIRONMENT:-test}"
  local stack_name="${TOPS_SNS_STACK:-teemops-messaging-${environment}}"

  if [[ ! -f "$SNS_TEMPLATE" ]]; then
    die "SNS template not found: $SNS_TEMPLATE"
  fi

  log "Deploying SNS stack ${stack_name}..."
  aws cloudformation deploy \
    --template-file "$SNS_TEMPLATE" \
    --stack-name "$stack_name" \
    --region "$AWS_DEFAULT_REGION" \
    --no-fail-on-empty-changeset \
    --parameter-overrides \
      "SQSLabel=teemops_main" \
    2>&1 | tee -a "$LOG_FILE"

  export SNS_STACK="$stack_name"
}

upload_child_account_template() {
  local bucket_name="$1"
  local template_path="${ROOT}/templates/iam.role.child.account.cfn.yaml"
  local s3_key="templates/iam.role.child.account.cfn.yaml"

  if [[ ! -f "$template_path" ]]; then
    die "Child account template not found: $template_path"
  fi

  log "Uploading child account CloudFormation template to s3://${bucket_name}/${s3_key}..."
  aws s3 cp "$template_path" "s3://${bucket_name}/${s3_key}" \
    --region "$AWS_DEFAULT_REGION" \
    2>&1 | tee -a "$LOG_FILE"

  export TOPS_CFN_TEMPLATE_URL="https://${bucket_name}.s3.${AWS_DEFAULT_REGION}.amazonaws.com/${s3_key}"
  log "Child account template URL: ${TOPS_CFN_TEMPLATE_URL}"
}

write_env_file() {
  local environment="${TOPS_ENVIRONMENT:-test}"
  local main_name main_arn audit_name audit_arn region_name region_arn bucket_name sns_arn

  main_name="$(cf_output "$CORE_STACK" TopsMainQueueName)"
  main_arn="$(cf_output "$CORE_STACK" TopsMainQueueArn)"
  audit_name="$(cf_output "$CORE_STACK" TopsAuditQueueName)"
  audit_arn="$(cf_output "$CORE_STACK" TopsAuditQueueArn)"
  region_name="$(cf_output "$CORE_STACK" TopsAuditRegionQueueName)"
  region_arn="$(cf_output "$CORE_STACK" TopsAuditRegionQueueArn)"
  bucket_name="$(cf_output "$CORE_STACK" DeploymentBucketName)"
  sns_arn="$(cf_output "$SNS_STACK" TopicArn)"

  for var_name in main_name main_arn audit_name audit_arn region_name region_arn bucket_name sns_arn; do
    if [[ -z "${!var_name}" || "${!var_name}" == "None" ]]; then
      die "Missing CloudFormation output: ${var_name}"
    fi
  done

  upload_child_account_template "$bucket_name"

  cat > "$ENV_FILE" <<EOF
# Generated by Teemops installer — do not edit manually
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
AWS_PARENT_ACCOUNT_ID=${DETECTED_AWS_ACCOUNT_ID}

TOPS_ENVIRONMENT=${environment}
TOPS_DEPLOYMENT_REGION=${AWS_DEFAULT_REGION}
TOPS_DEPLOY_BUCKET=${bucket_name}

TOPS_SQS_NAME=${main_name}
TOPS_SQS_ARN=${main_arn}
TOPS_AUDIT_SQS_NAME=${audit_name}
TOPS_AUDIT_SQS_ARN=${audit_arn}
TOPS_AUDIT_REGION_SQS_NAME=${region_name}
TOPS_AUDIT_REGION_SQS_ARN=${region_arn}

TOPS_SNS_ARN=${sns_arn}
TOPS_CFN_TEMPLATE_URL=${TOPS_CFN_TEMPLATE_URL}

SCAN_QUEUE_CONNECTION=sqs-audit
SCAN_REGION_QUEUE_CONNECTION=sqs-audit-region
QUEUE_CONNECTION=database
EOF

  log "Wrote ${ENV_FILE}"
  log "Restart app stack: docker compose up -d"
}

main() {
  : > "$LOG_FILE"
  load_dotenv
  require_region
  validate_aws_auth
  deploy_core_docker
  deploy_sns
  write_env_file
  log "Messaging install complete."
}

main "$@"
