#!/usr/bin/env bash
#
# Entrypoint for the backup scheduler container.
#
#   entrypoint.sh schedule        (default) bootstrap, then run supercronic
#   entrypoint.sh backup <args>   one-off:  docker compose run --rm backup backup full
#   entrypoint.sh restore <args>  one-off:  driven by ./backup.sh restore
#   entrypoint.sh <anything else> executed verbatim
#
# Bootstrap happens on every start and is idempotent, so the container is safe
# to restart and correct against a database that already existed before the
# scheduler was added (which /docker-entrypoint-initdb.d/ could not be — that
# only runs against an empty datadir).

set -Eeuo pipefail

RUNDIR=/run/tops-backup
BACKUP_DEFAULTS="$RUNDIR/my.cnf"
ROOT_DEFAULTS="$RUNDIR/root.cnf"
CRONTAB="$RUNDIR/crontab"

DB_HOST="${DB_HOST:-mysql}"
DB_PORT="${DB_PORT:-3306}"
DATADIR="${TOPS_MYSQL_DATADIR:-/var/lib/mysql}"

BACKUP_USER="${TOPS_BACKUP_USER:-tops_backup}"
BACKUP_PASSWORD="${TOPS_BACKUP_PASSWORD:-}"

log() { printf '%s [entrypoint] %s\n' "$(date '+%Y-%m-%d %H:%M:%S %Z')" "$*"; }

mkdir -p "$RUNDIR"
chmod 700 "$RUNDIR"

# ---------------------------------------------------------------------------
# Credentials
#
# Written to 0600 defaults-files rather than passed on the command line: every
# xtrabackup/mysql invocation would otherwise put the password in argv, where
# `ps` inside the container exposes it.
#
# Two identities, deliberately:
#   my.cnf   — least-privilege backup user. Enough to read the datadir
#              consistently and rotate binlogs, nothing more. Used by every
#              scheduled job, i.e. thousands of unattended runs.
#   root.cnf — only used by restore/replay, which applies arbitrary DDL and DML
#              out of the binary log and therefore genuinely needs full rights.
# ---------------------------------------------------------------------------

write_defaults() {
    local path="$1" user="$2" password="$3"
    umask 077
    cat >"$path" <<EOF
[client]
host=$DB_HOST
port=$DB_PORT
user=$user
password="$password"

[xtrabackup]
host=$DB_HOST
port=$DB_PORT
user=$user
password="$password"
datadir=$DATADIR

[mysqlbinlog]
host=$DB_HOST
port=$DB_PORT
user=$user
password="$password"

[mysqld]
datadir=$DATADIR
EOF
    chmod 600 "$path"
}

bootstrap_backup_user() {
    if [[ -z ${MYSQL_ROOT_PASSWORD:-} ]]; then
        log "MYSQL_ROOT_PASSWORD is not set — skipping backup-user bootstrap."
        log "  Scheduled backups will use whatever TOPS_BACKUP_USER credentials were supplied."
        log "  Restores need root: set MYSQL_ROOT_PASSWORD before running ./backup.sh restore."
        return 0
    fi

    write_defaults "$ROOT_DEFAULTS" root "$MYSQL_ROOT_PASSWORD"

    local waited=0
    until mysqladmin --defaults-file="$ROOT_DEFAULTS" ping --silent >/dev/null 2>&1; do
        (( waited >= 120 )) && { log "MySQL unreachable after 120s; continuing without bootstrap"; return 0; }
        sleep 2; waited=$(( waited + 2 ))
    done

    # These are exactly the grants Percona documents for XtraBackup 8.0, plus
    # RELOAD for the FLUSH BINARY LOGS the 15-minute archiver issues and
    # REPLICATION CLIENT for SHOW BINARY LOGS. Nothing here can read table data.
    mysql --defaults-file="$ROOT_DEFAULTS" <<SQL
CREATE USER IF NOT EXISTS '${BACKUP_USER}'@'%' IDENTIFIED BY '${BACKUP_PASSWORD}';
ALTER USER '${BACKUP_USER}'@'%' IDENTIFIED BY '${BACKUP_PASSWORD}';
GRANT BACKUP_ADMIN, PROCESS, RELOAD, LOCK TABLES, REPLICATION CLIENT ON *.* TO '${BACKUP_USER}'@'%';
GRANT SELECT ON performance_schema.log_status TO '${BACKUP_USER}'@'%';
GRANT SELECT ON performance_schema.keyring_component_status TO '${BACKUP_USER}'@'%';
GRANT SELECT ON performance_schema.replication_group_members TO '${BACKUP_USER}'@'%';
FLUSH PRIVILEGES;
SQL
    log "backup user '${BACKUP_USER}' bootstrapped with least-privilege grants"
}

# ---------------------------------------------------------------------------
# Schedule
# ---------------------------------------------------------------------------

write_crontab() {
    # The differential is offset ten minutes past the hour rather than on the
    # hour so it never contends with the 17:00 full. (The physical lock would
    # make a collision safe — the loser skips — but skipping the 17:00
    # differential silently would be a surprise, and a differential taken ten
    # minutes after its own base is nearly free.)
    cat >"$CRONTAB" <<EOF
# Generated by entrypoint.sh — edit the TOPS_BACKUP_*_CRON env vars instead.
# Times are ${TZ:-UTC}.

${TOPS_BACKUP_FULL_CRON:-0 17 * * *}    tops-backup full
${TOPS_BACKUP_DIFF_CRON:-10 * * * *}    tops-backup diff
${TOPS_BACKUP_BINLOG_CRON:-*/15 * * * *}    tops-backup binlog
${TOPS_BACKUP_PRUNE_CRON:-30 3 * * *}    tops-backup prune
EOF
    log "schedule (${TZ:-UTC}):"
    grep -vE '^\s*(#|$)' "$CRONTAB" | sed 's/^/  /'
}

# A scheduler that has never run leaves the system with nothing to restore
# from until the next 5pm. Take the first full immediately instead.
seed_first_full() {
    [[ ${TOPS_BACKUP_ON_START:-true} == true ]] || return 0
    if compgen -G "${TOPS_BACKUP_ROOT:-/backups}/full/*/META" >/dev/null; then
        return 0
    fi
    log "no full backup exists yet — taking a seed full backup now"
    tops-backup full || log "seed full backup failed; the scheduled run will retry"
}

# ---------------------------------------------------------------------------

case "${1:-schedule}" in
    schedule)
        write_defaults "$BACKUP_DEFAULTS" "$BACKUP_USER" "$BACKUP_PASSWORD"
        bootstrap_backup_user
        write_crontab
        seed_first_full
        log "starting supercronic"
        exec supercronic -passthrough-logs "$CRONTAB"
        ;;
    backup)
        shift
        write_defaults "$BACKUP_DEFAULTS" "$BACKUP_USER" "$BACKUP_PASSWORD"
        bootstrap_backup_user
        exec tops-backup "$@"
        ;;
    restore)
        shift
        write_defaults "$BACKUP_DEFAULTS" "$BACKUP_USER" "$BACKUP_PASSWORD"
        [[ -n ${MYSQL_ROOT_PASSWORD:-} ]] && write_defaults "$ROOT_DEFAULTS" root "$MYSQL_ROOT_PASSWORD"
        exec tops-restore "$@"
        ;;
    *)
        exec "$@"
        ;;
esac
